version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - app_network

  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: solver_db
    ports:
      - "5432:5432"
    networks:
      - app_network

  ci_cd:
    image: ghcr.io/actions/runner:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./github-runner:/runner
    environment:
      RUNNER_NAME: self-hosted-runner
      RUNNER_WORKDIR: /runner
      GITHUB_REPOSITORY: user/repository
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
